# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.39
_src_path: gh:oca/oca-addons-repo-template
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: true
enable_checklog_odoo: true
generate_requirements_txt: true
github_check_license: false
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_test_flavor: Odoo
odoo_version: 19.0
org_name: TheClaud99
org_slug: TheClaud99
rebel_module_groups: []
repo_description: Music Education
repo_name: music-education
repo_slug: music-education
repo_website: https://github.com/TheClaud99/music-education
use_pyproject_toml: true
use_ruff: true

